dist: xenial
os: linux
language: generic
go:
  - stable
services:
  - docker

jobs:
  include:
    - stage: build
      os: linux
      arch: amd64
      env:
       - BUILD_ARCH=amd64
       - BUILD_ARCH=arm32v6
       - BUILD_ARCH=arm32v7
      install:
       - 'echo ''{ "experimental": true }'' | sudo tee /etc/docker/daemon.json'
       - sudo systemctl restart docker
      before_script:
       - chmod -R g-w ./
      script:
       - ./build
      after_success:
       - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && ./push'
    - stage: build
      os: linux
      arch: arm64
      env:
       - BUILD_ARCH=arm64v8
      install:   
       - 'echo ''{ "experimental": true }'' | sudo tee /etc/docker/daemon.json'
       - sudo systemctl restart docker
      before_script:
       - chmod -R g-w ./
      script:   
       - ./build 
      after_success:
       - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && ./push'
    - stage: deploy
      name: "Create Manifest"
      install: 'mkdir $HOME/.docker/ && echo ''{ "experimental": "enabled" }'' > $HOME/.docker/config.json'
      before_script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      script: ./create-manifest
